import com.modrinth.minotaur.dependencies.ModDependency

plugins {
	id 'fabric-loom'
	id 'maven-publish'
  id "com.modrinth.minotaur"
}

base {
    archivesName = project.archives_base_name
}

loom {
	splitEnvironmentSourceSets()

    mods {
        "mc100days" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }

}

dependencies {
    // To change the versions see the gradle.properties file
    implementation project(':common')

    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // Fabric API. This is technically optional, but you probably want it anyway.
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    // Uncomment the following line to enable the deprecated Fabric API modules.
    // These are included in the Fabric API production distribution and allow you to update your mod to the latest modules at a later more convenient time.

    // modImplementation "net.fabricmc.fabric-api:fabric-api-deprecated:${project.fabric_version}"
}

processResources {
    inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

jar {
	inputs.property "archivesName", project.base.archivesName

    from(project(":common").sourceSets.main.output)

	from(rootProject.file("LICENSE")) {
		rename { "${it}_${inputs.properties.archivesName}"}
	}
}

// configure the maven publication
publishing {
	  publications {
	  	  create("mavenJava", MavenPublication) {
	  	  	  artifactId = project.archives_base_name
	  	  	  from components.java
	  	  }
	  }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
        // Notice: This block does NOT have the same function as the block in the top level.
        // The repositories here will be used for publishing your artifact, not for
        // retrieving dependencies.
    }
}

modrinth {
    token = System.getenv('MODRINTH_TOKEN')
    // Please use an environment variable for this! The default is `$MODRINTH_TOKEN`.
    projectId = "${project.modrinth_project_id}" // The ID of your Modrinth project. Slugs will not work.
    versionNumber = "v${project.mod_version}-mc${project.minecraft_version}"
    // The (preferably SemVer) version of the mod. If not specified, it'll use the `version` declaration
    versionName = "${project.mod_version}"  // The version title. If not specified, it'll use the version number
    uploadFile = remapJar // Tells Minotaur to use the remapped jar
    gameVersions = ['1.21.8'] // An array of game versions the version supports
    loaders = ['fabric'] // Self-explanatory.
    dependencies = [
            new ModDependency('P7dR8mSH', 'required') // Creates a new required dependency on Fabric API
    ]
}
