plugins {
    id 'net.fabricmc.fabric-loom' version '1.15-SNAPSHOT' apply false
    id 'net.neoforged.moddev' version '2.0.141' apply false
    id "com.modrinth.minotaur" version "2.+" apply false
}

group = project.maven_group
version = project.mod_version

subprojects {
    group = rootProject.group
    version = rootProject.version

    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        mavenCentral()
    }
}

tasks.register("modrinth") {
    group = "publishing"
    description = "Publishes Fabric and NeoForge builds to Modrinth."
    dependsOn(":fabric:modrinth", ":neoforge:modrinth")
}
