# Done to increase the memory available to gradle.
# Force IPv4 to avoid wildcard IP resolution issues in the sandboxed environment.
org.gradle.jvmargs=-Xmx1G -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv6Addresses=false
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=1.1.0
maven_group=me.datsuns.mc100days
archives_base_name=mc100days

# for ferry.gradle
archive_name=mc100days

# Modrinth
modrinth_project_id = DsrqhD5F

# Dependencies
fabric_api_version=0.150.0+26.1.2

# NeoForge Properties
neo_version=26.1.2.73
minecraft_version_range=[26.1.2]

# Shared Mod Metadata
mod_id=mc100days
mod_name=mc100days
mod_license=CC0-1.0
mod_authors=datsuns
mod_group_id=me.datsuns.mc100days
mod_description=Utility for Playing 100days Adventure !
