# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.10
yarn_mappings=1.21.10+build.1
loader_version=0.17.2
loom_version=1.11-SNAPSHOT

# Mod Properties
mod_version=1.1.0
maven_group=me.datsuns.mc100days
archives_base_name=mc100days

# for ferry.gradle
archive_name=mc100days

# Modrinth
modrinth_project_id = DsrqhD5F

# Dependencies
fabric_version=0.138.3+1.21.10

# NeoForge Properties
neo_version=21.10.49-beta
minecraft_version_range=[1.21.10]
parchment_minecraft_version=1.21.10
parchment_mappings_version=2025.10.12

# Shared Mod Metadata
mod_id=mc100days
mod_name=mc100days
mod_license=CC0-1.0
mod_authors=datsuns
mod_group_id=me.datsuns.mc100days
mod_description=Utility for Playing 100days Adventure !
