plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev'
    id 'idea'
    id "com.modrinth.minotaur"
}


base {
    archivesName = project.archives_base_name
}

def neoforgeJarName = { suffix ->
    "${project.archives_base_name}-${project.version}-neoforge-mc${project.minecraft_version}${suffix}"
}

java {
    withSourcesJar()
    toolchain.languageVersion = JavaLanguageVersion.of(25)
}
tasks.named("jar") {
    archiveFileName = neoforgeJarName(".jar")

    from(project(":common").sourceSets.main.output)

    from(rootProject.file("LICENSE")) {
        rename { "${it}_${project.archives_base_name}" }
    }
}

neoForge {
    version = project.neo_version



    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            clientData()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${project.mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
    localRuntime
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    implementation project(':common')
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}
sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

tasks.named("sourcesJar") {
    archiveFileName = neoforgeJarName("-sources.jar")

    from(project(":common").sourceSets.main.allSource)
}

modrinth {
    token = System.getenv('MODRINTH_TOKEN')
    projectId = "${project.modrinth_project_id}"
    versionNumber = "v${project.mod_version}-mc${project.minecraft_version}-neoforge"
    versionName = "${project.mod_version}-NeoForge for Minecraft v${project.minecraft_version}"
    uploadFile = jar
    gameVersions = [project.minecraft_version]
    loaders = ['neoforge']
}
